pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - check-success="Tests Normal"
      - check-success="Tests Madsim"
      - check-success="Commit Message Validation"
      - check-success="Spell Check"
      - check-success="Build"
      - check-success="E2E kube"
      - check-success="Validation"
      - check-success="DCO"
      - check-success="codecov/project"
      - check-success="codecov/patch"
      - or:
        - "#approved-reviews-by >= 2"
        - and:
          - author = dependabot[bot]
          - "#approved-reviews-by>=1"
    actions:
      merge:
        method: rebase

  - name: convert to draft
    conditions:
      - and:
          - "#check-failure>0"
          - -check-failure~=codecov/.*
    actions:
      comment:
        message: "@{{author}} Convert your pr to draft since CI failed"
      edit:
        draft: true

  - name: automatic approval for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success="Tests Normal"
      - check-success="Tests Madsim"
      - check-success="Commit Message Validation"
      - check-success="Spell Check"
      - check-success="Build"
      - check-success="E2E kube"
      - check-success="Validation"
      - check-success="DCO"
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot

  - name: rebase pull request when it's more than 10 commits behind main
    conditions:
      - "#commits-behind>=10"
    actions:
      rebase:

  - name: balanced review assignment
    conditions:
      - author!=dependabot[bot]
    actions:
      request_reviews:
        teams:
          - "@XlineTeam"
        random_count: 2

  - name: comment when a pull request cannot be merged
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} Your PR is in conflict and cannot be merged."

  - name: comment when modify workflow
    conditions:
      - files ~= ^\.github/workflows/
    actions:
      comment:
        message: "@{{author}} You've modified the workflows. Please don't forget to update the .mergify.yml."
