/// Auth command
pub(crate) mod auth;
/// Compaction command
pub(crate) mod compaction;
/// Delete command
pub(crate) mod delete;
/// Get command
pub(crate) mod get;
/// Lease command
pub(crate) mod lease;
/// Lock command
pub(crate) mod lock;
/// Member command
pub(crate) mod member;
/// Put command
pub(crate) mod put;
/// Role command
pub(crate) mod role;
/// Snapshot command
pub(crate) mod snapshot;
/// Txn command
pub(crate) mod txn;
/// User command
pub(crate) mod user;
/// Watch command
pub(crate) mod watch;
