global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "xline"
    static_configs:
      - targets:
          [
            "node1:9100",
            "node2:9100",
            "node3:9100",
          ]
    metrics_path: /metrics
    scheme: http
