name: Build Env Image

on:
  workflow_dispatch: {}
  pull_request:
    branches: [master]

jobs:
  build-env:
    runs-on: ubuntu-latest
    name: Try to build env
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files in ci
        id: changed-files-ci
        uses: tj-actions/changed-files@v40
        with:
          files: ci/{Dockerfile,build-env.sh}
      - name: Run build env if changes
        if: steps.changed-files-ci.outputs.any_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ci/build-env.sh
