on:
  issues:
    types:
      - opened

# https://github.com/marketplace/actions/create-or-update-comment

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            👋 Thanks for opening this issue!

            Reply with the following command on its own line to get help or engage:

            - `/contributing-agreement` : to print Contributing Agreements.
            - `/assignme` : to assign this issue to you.
