on:
  workflow_call:
    inputs:
      app_version:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  REGISTRY_IMAGE: datenlord/xline

jobs:
  merge_image:
    runs-on: ubuntu-latest
    name: Merge Docker Image
    steps:
      - name: Download Digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: /tmp/digests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Manifest
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
                      -t ${{ env.REGISTRY_IMAGE }}:latest \
                      -t ${{ env.REGISTRY_IMAGE }}:${{ inputs.app_version }} \
                      $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect Manifest
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ inputs.app_version }}
