name: Merge Multi-platform Image Manifests

on:
  workflow_call:
    inputs:
      app_version:
        required: true
        type: string

env:
  IMAGE_ID: ghcr.io/xline-kv/xline

jobs:
  merge_image:
    runs-on: ubuntu-latest
    name: Merge Docker Image
    steps:
      - name: Download Digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: /tmp/digests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: xline-kv
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Manifest
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
                      -t ${{ env.IMAGE_ID }}:latest \
                      -t ${{ env.IMAGE_ID }}:${{ inputs.app_version }} \
                      $(printf '${{ env.IMAGE_ID }}@sha256:%s ' *)

      - name: Inspect Manifest
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_ID }}:${{ inputs.app_version }}
